spring.application.name=Reddit

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d889ljl7vvec738jc8cg-a:5432/devsphere_db
spring.datasource.username=devsphere_db_user
spring.datasource.password=8nP2fT1OJ1xVKV95dxjupJJznJcAKPU1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:mysecretkey123}