spring.application.name=Reddit

server.port=${PORT:8080}

spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:postgresql://devsphere_db_user:8nP2fT1OJ1xVKV95dxjupJJznJcAKPU1@dpg-d889ljl7vvec738jc8cg-a/devsphere_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devsphere_db_user}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:8nP2fT1OJ1xVKV95dxjupJJznJcAKPU1}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:mysecretkey123}